-- Belen Creator - Schema con Supabase Auth + RLS
-- Este archivo documenta el schema esperado. La BD real se gestiona via Supabase.

CREATE TABLE usuario (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid() REFERENCES auth.users(id) ON DELETE CASCADE,
    ipv4 TEXT,
    permiso TEXT DEFAULT 'user',
    nombre TEXT,
    correo TEXT
);

CREATE TABLE tipo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT,
    acciones TEXT DEFAULT '{}',
    params TEXT
);

CREATE TABLE propietario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT
);

CREATE TABLE ubicacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL
);

CREATE TABLE pieza (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT UNIQUE,
    nombre TEXT,
    notas TEXT,
    fecha DATE,
    precio NUMERIC(10,2),
    propietario_id BIGINT NOT NULL REFERENCES propietario(id),
    ubicacion_id BIGINT REFERENCES ubicacion(id),
    largo_cm NUMERIC(10,2),
    ancho_cm NUMERIC(10,2),
    alto_cm NUMERIC(10,2)
);

-- Valores concretos de variables extra por enlace pieza–tipo (definición en tipo.params), p. ej. {"longitud": 10}
CREATE TABLE pieza_tipo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pieza_id BIGINT NOT NULL REFERENCES pieza(id) ON DELETE CASCADE,
    tipo_id BIGINT NOT NULL REFERENCES tipo(id) ON DELETE CASCADE,
    params JSONB DEFAULT '{}',
    UNIQUE (pieza_id, tipo_id)
);

CREATE TABLE galeria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT,
    formato TEXT,
    base64 TEXT,
    pieza_id BIGINT NOT NULL REFERENCES pieza(id),
    orden INTEGER DEFAULT 0
);

-- params (JSONB): "modo", "ciclos"; "dimensiones": {"longitud": cm, "anchura": cm} del tablero canvas superior.
CREATE TABLE timeline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    params JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE puerto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT,
    tipo_id BIGINT NOT NULL REFERENCES tipo(id),
    pin INTEGER,
    params TEXT DEFAULT '{}'
);

CREATE TABLE usada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time TEXT,
    accion TEXT,
    params TEXT,
    pieza_id BIGINT NOT NULL REFERENCES pieza(id),
    timeline_id BIGINT NOT NULL REFERENCES timeline(id),
    puerto_id BIGINT REFERENCES puerto(id)
);

CREATE TABLE bluetooth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    direccion TEXT NOT NULL
);

CREATE TABLE historial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla TEXT NOT NULL,
    texto TEXT NOT NULL,
    antes JSONB,
    despues JSONB,
    usuario_id UUID REFERENCES usuario(id) ON DELETE SET NULL,
    fecha TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS historial_usuario_id_idx ON historial (usuario_id);

-- Funcion auxiliar para RLS
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.usuario
    WHERE id = auth.uid() AND permiso = 'admin'
  );
$$ LANGUAGE sql STABLE SECURITY DEFINER;

-- Trigger: crear perfil automaticamente al registrar en Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.usuario (id, nombre, correo, permiso, ipv4)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'nombre', ''),
    new.email,
    'user',
    COALESCE(new.raw_user_meta_data->>'ipv4', '')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- RLS habilitado en TODAS las tablas. Políticas concretas: ../rls/rls_policies.sql
ALTER TABLE usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE tipo ENABLE ROW LEVEL SECURITY;
ALTER TABLE propietario ENABLE ROW LEVEL SECURITY;
ALTER TABLE ubicacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE pieza ENABLE ROW LEVEL SECURITY;
ALTER TABLE pieza_tipo ENABLE ROW LEVEL SECURITY;
ALTER TABLE galeria ENABLE ROW LEVEL SECURITY;
ALTER TABLE timeline ENABLE ROW LEVEL SECURITY;
ALTER TABLE puerto ENABLE ROW LEVEL SECURITY;
ALTER TABLE usada ENABLE ROW LEVEL SECURITY;
ALTER TABLE bluetooth ENABLE ROW LEVEL SECURITY;
ALTER TABLE historial ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------------------------
-- Nota 2026-04: `pieza.params` eliminado en producción. Los valores por tipo viven
-- en `pieza_tipo.params` (JSONB). Migración remota Supabase: pieza_params_to_pieza_tipo
-- ------------------------------------------------------------------------------
